/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CommonWalletV1,
  CommonWalletV1Interface,
} from "../CommonWalletV1";

const _abi = [
  {
    inputs: [],
    name: "xChangeContract",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class CommonWalletV1__factory {
  static readonly abi = _abi;
  static createInterface(): CommonWalletV1Interface {
    return new utils.Interface(_abi) as CommonWalletV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CommonWalletV1 {
    return new Contract(address, _abi, signerOrProvider) as CommonWalletV1;
  }
}
